//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoGupar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public string id { get; set; }
        public string idTipoMovimiento { get; set; }
        public string idAlmacen { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string descripcion { get; set; }
    
        public virtual TiposMovimiento TiposMovimiento { get; set; }
    }
}
